"""empty message

Revision ID: 00f57130817c
Revises: 
Create Date: 2022-06-17 16:39:46.426652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00f57130817c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.String(length=30), nullable=False),
    sa.Column('car_id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('car_type', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
