"""empty message

Revision ID: 37e7433fe949
Revises: 
Create Date: 2022-06-18 00:09:19.510339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37e7433fe949'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('common_fault',
    sa.Column('common_fault_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cell_fault', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cell_fault'], ['cell_fault.fault_id'], ),
    sa.PrimaryKeyConstraint('common_fault_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('common_fault')
    # ### end Alembic commands ###
