"""empty message

Revision ID: 7a0cb1100d0a
Revises: 3c79ca63799e
Create Date: 2022-06-19 23:56:15.292951

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a0cb1100d0a'
down_revision = '3c79ca63799e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solution', 'picture')
    op.add_column('step', sa.Column('picture_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'step', 'picture', ['picture_id'], ['picture_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'step', type_='foreignkey')
    op.drop_column('step', 'picture_id')
    op.add_column('solution', sa.Column('picture', mysql.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
